2018-05-22 13:13:12,591 - TCP Server Channel - ERROR - data receive failed
Traceback (most recent call last):
  File "/home/zen/git/plumber/PlumberClient/TCPServerForwarder.py", line 54, in get_data
    data = self.request.recv(1024)
error: [Errno 104] Connection reset by peer
2018-05-22 13:27:13,337 - TCP Server Channel - ERROR - data receive failed
Traceback (most recent call last):
  File "/home/zen/git/plumber/PlumberClient/TCPServerForwarder.py", line 54, in get_data
    data = self.request.recv(1024)
error: [Errno 104] Connection reset by peer
2018-05-22 13:27:13,337 - root - ERROR - read data from in_queue failed
Traceback (most recent call last):
  File "/home/zen/git/plumber/PlumberClient/TCPServerForwarder.py", line 73, in write_data
    self.request.sendall(data)
  File "/home/zen/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
